// PDF generation using jsPDF + jspdf-autotable
// Runs only on server (API routes)

import fs from 'fs'
import path from 'path'
import { formatDate, getDaysOverdue } from './utils'

// ── jsPDF's built-in Helvetica has no ₹ glyph — use "Rs." for PDFs ──────────
function pdfRs(amount: number): string {
  return `Rs. ${amount.toLocaleString('en-IN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

// ── Read SIRPL logo once (server-side) ───────────────────────────────────────
function getLogoBase64(): string | null {
  try {
    const p = path.join(process.cwd(), 'public', 'sirpl-logo.png')
    return fs.readFileSync(p).toString('base64')
  } catch {
    return null
  }
}

// ── Shared header: logo + company name + accent line ─────────────────────────
function drawHeader(
  doc: any,
  w: number,
  margin: number,
  logo: string | null,
  business: { name: string; gstin?: string | null },
  rightLines: string[],
  title: string
): number {
  const logoSize = 18
  const logoX = margin
  const logoY = 10

  if (logo) {
    doc.addImage(logo, 'PNG', logoX, logoY, logoSize, logoSize)
  }

  const textX = logo ? logoX + logoSize + 4 : logoX

  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(17, 24, 39)
  doc.text('SIRPL', textX, 17)

  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(75, 85, 99)
  doc.text('Samwha India Refractories Pvt. Ltd.', textX, 22)
  if (business.gstin) doc.text(`GSTIN: ${business.gstin}`, textX, 27)

  // Right side info
  doc.setFontSize(8)
  doc.setTextColor(75, 85, 99)
  rightLines.forEach((line, i) => {
    doc.text(line, w - margin, 17 + i * 5, { align: 'right' })
  })

  // Blue accent line
  const lineY = Math.max(logoY + logoSize, 32) + 3
  doc.setFillColor(37, 99, 235)
  doc.rect(0, lineY, w, 1.5, 'F')

  // Document title below accent line
  const titleY = lineY + 9
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(17, 24, 39)
  doc.text(title, margin, titleY)

  return titleY + 8
}

// ── Shared footer ─────────────────────────────────────────────────────────────
function drawFooter(doc: any, w: number) {
  const h = doc.internal.pageSize.getHeight()
  doc.setDrawColor(229, 231, 235)
  doc.line(20, h - 15, w - 20, h - 15)
  doc.setFontSize(7.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(156, 163, 175)
  doc.text('Samwha India Refractories Pvt. Ltd.  |  Generated by SIRPL', w / 2, h - 9, { align: 'center' })
}

interface BusinessInfo {
  name: string
  gstin?: string | null
  phone?: string | null
  email?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  pincode?: string | null
}

interface ClientInfo {
  name: string
  email?: string | null
  phone?: string | null
  gstin?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
}

interface InvoiceInfo {
  invoice_number: string
  amount: number
  tax_amount: number
  total_amount: number
  issue_date: string
  due_date: string
  description?: string | null
  status: string
}

// ── Outstanding Payment Statement (attached to reminder emails) ───────────────
export async function generateReminderPDF(
  business: BusinessInfo,
  client: ClientInfo,
  invoice: InvoiceInfo & { paid_amount?: number | null }
): Promise<ArrayBuffer> {
  const { jsPDF } = await import('jspdf')
  const autoTable = (await import('jspdf-autotable')).default

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const w = doc.internal.pageSize.getWidth()
  const margin = 20
  const logo = getLogoBase64()

  const daysOverdue = getDaysOverdue(invoice.due_date)
  const paidAmount = Number(invoice.paid_amount || 0)
  const outstanding = invoice.total_amount - paidAmount

  // Header
  let y = drawHeader(
    doc, w, margin, logo,
    business,
    [`Date: ${formatDate(new Date().toISOString())}`, `Ref: ${invoice.invoice_number}`],
    'Outstanding Payment Statement'
  )

  // ── Bill To ──────────────────────────────────────────────────────────────────
  y += 2
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(107, 114, 128)
  doc.text('BILL TO', margin, y)
  y += 5

  const toLines = [
    client.name,
    client.address,
    [client.city, client.state].filter(Boolean).join(', '),
    client.gstin ? `GSTIN: ${client.gstin}` : null,
    client.phone,
    client.email,
  ].filter((l): l is string => !!l)

  doc.setFontSize(9)
  toLines.forEach((line, i) => {
    doc.setFont('helvetica', i === 0 ? 'bold' : 'normal')
    doc.setTextColor(17, 24, 39)
    doc.text(line, margin, y)
    y += 5
  })

  // ── Invoice details — clean 2-column key-value table ─────────────────────────
  y += 6

  const rows: [string, string][] = [
    ['Invoice Number', invoice.invoice_number],
    ['Invoice Date', formatDate(invoice.issue_date)],
    ['Due Date', formatDate(invoice.due_date)],
    ['Days Overdue', daysOverdue > 0 ? `${daysOverdue} days` : 'Due today'],
    ['Invoice Total', pdfRs(invoice.total_amount)],
  ]
  if (paidAmount > 0) {
    rows.push(['Amount Received', pdfRs(paidAmount)])
  }

  autoTable(doc, {
    startY: y,
    head: [],
    body: rows,
    margin: { left: margin, right: margin },
    styles: { fontSize: 9.5, cellPadding: { top: 4, bottom: 4, left: 6, right: 6 } },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: [75, 85, 99], cellWidth: 60 },
      1: { textColor: [17, 24, 39], cellWidth: 'auto' },
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    tableLineColor: [229, 231, 235],
    tableLineWidth: 0.3,
  })

  const afterTable = (doc as any).lastAutoTable.finalY

  // ── Outstanding amount highlight row ─────────────────────────────────────────
  const boxH = 14
  const boxY = afterTable
  doc.setFillColor(239, 68, 68)   // red-500
  doc.rect(margin, boxY, w - margin * 2, boxH, 'F')

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text('AMOUNT OUTSTANDING', margin + 4, boxY + 5.5)

  doc.setFontSize(13)
  doc.text(pdfRs(outstanding), w - margin - 4, boxY + 9.5, { align: 'right' })

  // ── Note ─────────────────────────────────────────────────────────────────────
  y = boxY + boxH + 10
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(55, 65, 81)

  const contact = business.email || business.phone || ''
  const noteText = `Kindly arrange payment of ${pdfRs(outstanding)} at the earliest. For any queries, please contact us${contact ? ` at ${contact}` : ''}.`
  const noteLines = doc.splitTextToSize(noteText, w - margin * 2)
  doc.text(noteLines, margin, y)
  y += noteLines.length * 5 + 8

  // Contact block
  if (business.phone || business.email) {
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(17, 24, 39)
    doc.text('For payment / queries:', margin, y)
    y += 5
    doc.setFont('helvetica', 'normal')
    if (business.phone) { doc.text(business.phone, margin, y); y += 5 }
    if (business.email) { doc.text(business.email, margin, y); y += 5 }
  }

  drawFooter(doc, w)
  return doc.output('arraybuffer')
}

// ── Invoice PDF ───────────────────────────────────────────────────────────────
export async function generateInvoicePDF(
  business: BusinessInfo,
  client: ClientInfo,
  invoice: InvoiceInfo
): Promise<ArrayBuffer> {
  const { jsPDF } = await import('jspdf')
  const autoTable = (await import('jspdf-autotable')).default

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const w = doc.internal.pageSize.getWidth()
  const margin = 20
  const logo = getLogoBase64()

  // Header
  let y = drawHeader(
    doc, w, margin, logo,
    business,
    [`Invoice No: ${invoice.invoice_number}`, `Date: ${formatDate(invoice.issue_date)}`, `Due: ${formatDate(invoice.due_date)}`],
    'TAX INVOICE'
  )

  // ── From / Bill To ────────────────────────────────────────────────────────────
  y += 2
  const colMid = w / 2

  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(107, 114, 128)
  doc.text('FROM', margin, y)
  doc.text('BILL TO', colMid, y)
  y += 5

  const fromLines = [
    business.name,
    business.address,
    [business.city, business.state, business.pincode].filter(Boolean).join(', '),
    business.gstin ? `GSTIN: ${business.gstin}` : null,
    business.phone,
    business.email,
  ].filter((l): l is string => !!l)

  const toLines = [
    client.name,
    client.address,
    [client.city, client.state].filter(Boolean).join(', '),
    client.gstin ? `GSTIN: ${client.gstin}` : null,
    client.phone,
    client.email,
  ].filter((l): l is string => !!l)

  doc.setFontSize(9)
  fromLines.forEach((line, i) => {
    doc.setFont('helvetica', i === 0 ? 'bold' : 'normal')
    doc.setTextColor(17, 24, 39)
    doc.text(line, margin, y + i * 5)
  })
  toLines.forEach((line, i) => {
    doc.setFont('helvetica', i === 0 ? 'bold' : 'normal')
    doc.setTextColor(17, 24, 39)
    doc.text(line, colMid, y + i * 5)
  })

  y += Math.max(fromLines.length, toLines.length) * 5 + 10

  // ── Items table ───────────────────────────────────────────────────────────────
  const gstRate = invoice.amount > 0
    ? ((invoice.tax_amount / invoice.amount) * 100).toFixed(0)
    : '0'

  autoTable(doc, {
    startY: y,
    head: [['Description', 'Amount (Rs.)']],
    body: [
      [invoice.description || 'Supply of Goods / Services', pdfRs(invoice.amount)],
      [`GST @ ${gstRate}%`, pdfRs(invoice.tax_amount)],
    ],
    foot: [['Total', pdfRs(invoice.total_amount)]],
    margin: { left: margin, right: margin },
    headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold', fontSize: 9.5 },
    footStyles: { fillColor: [241, 245, 249], textColor: [17, 24, 39], fontStyle: 'bold', fontSize: 10.5 },
    styles: { fontSize: 9.5, cellPadding: 5 },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold', cellWidth: 50 } },
  })

  const finalY = (doc as any).lastAutoTable.finalY + 10

  // Status badge
  const isPaid = invoice.status === 'paid'
  doc.setFillColor(...(isPaid ? [220, 252, 231] : [254, 226, 226]) as [number, number, number])
  doc.setDrawColor(...(isPaid ? [134, 239, 172] : [252, 165, 165]) as [number, number, number])
  doc.roundedRect(margin, finalY, w - margin * 2, 11, 2, 2, 'FD')
  doc.setFontSize(9.5)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(...(isPaid ? [21, 128, 61] : [185, 28, 28]) as [number, number, number])
  doc.text(
    isPaid ? 'PAID' : `PAYMENT DUE — ${formatDate(invoice.due_date)}`,
    w / 2, finalY + 7.5, { align: 'center' }
  )

  drawFooter(doc, w)
  return doc.output('arraybuffer')
}

// ── Legal Notice PDF ──────────────────────────────────────────────────────────
export async function generateLegalNoticePDF(
  business: BusinessInfo,
  client: ClientInfo,
  invoice: InvoiceInfo
): Promise<ArrayBuffer> {
  const { jsPDF } = await import('jspdf')
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const w = doc.internal.pageSize.getWidth()
  const margin = 25
  const logo = getLogoBase64()
  const daysOverdue = getDaysOverdue(invoice.due_date)

  let y = drawHeader(
    doc, w, margin, logo,
    business,
    [`Date: ${formatDate(new Date().toISOString())}`, `Ref: LEGAL-${invoice.invoice_number}`],
    'Legal Notice'
  )

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(17, 24, 39)
  doc.text('From:', margin, y); y += 5
  const fromInfo = [business.name, business.address, [business.city, business.state, business.pincode].filter(Boolean).join(', '), business.gstin ? `GSTIN: ${business.gstin}` : null, business.phone, business.email].filter((l): l is string => !!l)
  doc.setFont('helvetica', 'normal')
  fromInfo.forEach(line => { doc.text(line, margin + 4, y); y += 5 })
  y += 4

  doc.setFont('helvetica', 'bold')
  doc.text('To:', margin, y); y += 5
  const toInfo = [client.name, client.address, [client.city, client.state].filter(Boolean).join(', '), client.gstin ? `GSTIN: ${client.gstin}` : null, client.phone, client.email].filter((l): l is string => !!l)
  doc.setFont('helvetica', 'normal')
  toInfo.forEach(line => { doc.text(line, margin + 4, y); y += 5 })
  y += 6

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(10)
  const subj = `Subject: Recovery of outstanding payment of ${pdfRs(invoice.total_amount)} against Invoice No. ${invoice.invoice_number}`
  const subjLines = doc.splitTextToSize(subj, w - margin * 2)
  doc.text(subjLines, margin, y)
  y += subjLines.length * 5 + 6

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9.5)

  const bodyParagraphs = [
    `Sir/Madam,`,
    `Under instructions from M/s ${business.name}, we hereby serve this Legal Notice upon you:`,
    `1. Our client supplied goods/services as per Invoice No. ${invoice.invoice_number} dated ${formatDate(invoice.issue_date)} for ${pdfRs(invoice.amount)} plus GST of ${pdfRs(invoice.tax_amount)}, totalling ${pdfRs(invoice.total_amount)}.`,
    `2. The said invoice was payable on or before ${formatDate(invoice.due_date)}. Despite ${daysOverdue} days having elapsed and repeated reminders, you have failed to make the payment.`,
    `3. Your failure to pay constitutes a breach of contract and is in violation of Section 16 of the MSME Development Act, 2006.`,
    `4. You are hereby called upon to pay ${pdfRs(invoice.total_amount)} along with interest at 3 times the bank rate within 15 days of receipt of this notice.`,
    `5. Failure to comply will compel our client to initiate proceedings before the MSME Facilitation Council / Samadhaan portal, at your cost and risk.`,
    `Yours faithfully,`,
    business.name + (business.phone ? `   |   ${business.phone}` : '') + (business.email ? `   |   ${business.email}` : ''),
  ]

  bodyParagraphs.forEach(para => {
    const lines = doc.splitTextToSize(para, w - margin * 2)
    doc.text(lines, margin, y)
    y += lines.length * 5 + 3
  })

  drawFooter(doc, w)
  return doc.output('arraybuffer')
}

// ── MSME Complaint PDF ────────────────────────────────────────────────────────
export async function generateMSMEComplaintPDF(
  business: BusinessInfo,
  client: ClientInfo,
  invoice: InvoiceInfo
): Promise<ArrayBuffer> {
  const { jsPDF } = await import('jspdf')
  const autoTable = (await import('jspdf-autotable')).default
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const w = doc.internal.pageSize.getWidth()
  const margin = 20
  const logo = getLogoBase64()

  let y = drawHeader(
    doc, w, margin, logo,
    business,
    [`Date: ${formatDate(new Date().toISOString())}`],
    'MSME Samadhaan — Complaint Draft'
  )

  const fields: [string, string][] = [
    ['Applicant Name', business.name],
    ['Applicant GSTIN', business.gstin || 'N/A'],
    ['Applicant Contact', [business.phone, business.email].filter(Boolean).join(' / ')],
    ['Applicant Address', [business.address, business.city, business.state, business.pincode].filter(Boolean).join(', ')],
    ['Respondent Name', client.name],
    ['Respondent GSTIN', client.gstin || 'N/A'],
    ['Respondent Contact', [client.phone, client.email].filter(Boolean).join(' / ')],
    ['Respondent Address', [client.address, client.city, client.state].filter(Boolean).join(', ')],
    ['Invoice Number', invoice.invoice_number],
    ['Invoice Date', formatDate(invoice.issue_date)],
    ['Invoice Amount', pdfRs(invoice.amount)],
    ['GST Amount', pdfRs(invoice.tax_amount)],
    ['Total Claimed', pdfRs(invoice.total_amount)],
    ['Due Date', formatDate(invoice.due_date)],
    ['Days Overdue', `${getDaysOverdue(invoice.due_date)} days`],
    ['Nature of Dispute', 'Non-payment of dues for goods/services supplied'],
    ['Relief Sought', `Recovery of ${pdfRs(invoice.total_amount)} with interest at 3x bank rate`],
  ]

  autoTable(doc, {
    startY: y,
    body: fields,
    margin: { left: margin, right: margin },
    styles: { fontSize: 9, cellPadding: 3.5 },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: [75, 85, 99], cellWidth: 65 },
      1: { textColor: [17, 24, 39] },
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
  })

  y = (doc as any).lastAutoTable.finalY + 10
  doc.setFontSize(8.5)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(75, 85, 99)
  const declaration = `I/We declare that the above information is true and correct. I/We have not approached any court of law in respect of the above dispute.`
  const declLines = doc.splitTextToSize(declaration, w - margin * 2)
  doc.text(declLines, margin, y)
  y += declLines.length * 5 + 12
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(17, 24, 39)
  doc.text('Signature: ___________________________', margin, y)
  y += 6
  doc.setFont('helvetica', 'normal')
  doc.text(`Name: ${business.name}`, margin, y)
  y += 6
  doc.text(`Date: ${formatDate(new Date().toISOString())}`, margin, y)

  drawFooter(doc, w)
  return doc.output('arraybuffer')
}

// ── Transport Award PDF ───────────────────────────────────────────────────────
interface TransportAwardInfo {
  loadId: string
  pickup: string
  drop: string
  material: string
  weight: string
  vehicleType: string
  finalAmount: number
  transporterName: string
  pickupDate: string
  awardedAt: string
}

export async function generateTransportAwardPDF(info: TransportAwardInfo): Promise<ArrayBuffer> {
  const { jsPDF } = await import('jspdf')
  const autoTable = (await import('jspdf-autotable')).default

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const w = doc.internal.pageSize.getWidth()
  const margin = 20
  const logo = getLogoBase64()

  const pickupDateStr = new Date(info.pickupDate).toLocaleDateString('en-IN', {
    day: '2-digit', month: 'long', year: 'numeric',
  })
  const awardedAtStr = new Date(info.awardedAt).toLocaleString('en-IN', {
    day: '2-digit', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit',
  })

  // Header
  let y = drawHeader(
    doc, w, margin, logo,
    { name: 'Samwha India Refractories Pvt. Ltd.' },
    [`Date: ${awardedAtStr}`, `Load ID: ${info.loadId}`],
    'Transport Load Award Confirmation'
  )

  y += 6
  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(107, 114, 128)
  doc.text('AWARDED TO', margin, y)
  y += 5
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(17, 24, 39)
  doc.text(info.transporterName, margin, y)
  y += 10

  const rows: [string, string][] = [
    ['Load ID', info.loadId],
    ['Pickup Location', info.pickup],
    ['Drop Location', info.drop],
    ['Material', info.material],
    ['Weight', info.weight],
    ['Vehicle Type', info.vehicleType],
    ['Pickup Date', pickupDateStr],
    ['Awarded On', awardedAtStr],
  ]

  autoTable(doc, {
    startY: y,
    head: [],
    body: rows,
    margin: { left: margin, right: margin },
    styles: { fontSize: 10, cellPadding: { top: 4, bottom: 4, left: 6, right: 6 } },
    columnStyles: {
      0: { fontStyle: 'bold', textColor: [75, 85, 99], cellWidth: 65 },
      1: { textColor: [17, 24, 39] },
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    tableLineColor: [229, 231, 235],
    tableLineWidth: 0.3,
  })

  const afterTable = (doc as any).lastAutoTable.finalY

  // Awarded amount highlight
  const boxH = 16
  const boxY = afterTable + 4
  doc.setFillColor(22, 163, 74) // green-600
  doc.rect(margin, boxY, w - margin * 2, boxH, 'F')

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  doc.text('AWARDED AMOUNT', margin + 4, boxY + 6)

  doc.setFontSize(14)
  doc.text(
    `Rs. ${info.finalAmount.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`,
    w - margin - 4, boxY + 11, { align: 'right' }
  )

  const noteY = boxY + boxH + 12
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(55, 65, 81)
  const noteText = `This document serves as official confirmation that the above-mentioned transporter has been awarded the freight load. Please retain this for your records. Our operations team will reach out with further logistics details.`
  const noteLines = doc.splitTextToSize(noteText, w - margin * 2)
  doc.text(noteLines, margin, noteY)

  drawFooter(doc, w)
  return doc.output('arraybuffer')
}

// ── Report CSV ────────────────────────────────────────────────────────────────
export async function generateReportCSV(invoices: any[]): Promise<string> {
  const headers = ['Invoice Number', 'Client', 'Amount', 'GST', 'Total', 'Issue Date', 'Due Date', 'Status', 'Paid Date', 'Days Overdue']
  const rows = invoices.map(inv => [
    inv.invoice_number,
    inv.client?.name || '',
    inv.amount,
    inv.tax_amount,
    inv.total_amount,
    inv.issue_date,
    inv.due_date,
    inv.status,
    inv.paid_at ? inv.paid_at.split('T')[0] : '',
    inv.status === 'overdue' ? getDaysOverdue(inv.due_date) : '',
  ])
  return [headers, ...rows].map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(',')).join('\n')
}
