// PDF generation using jsPDF + jspdf-autotable
// Runs only on server (API routes)

import { formatCurrency, formatDate, getDaysOverdue } from './utils'

interface BusinessInfo {
  name: string
  gstin?: string | null
  phone?: string | null
  email?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
  pincode?: string | null
}

interface ClientInfo {
  name: string
  email?: string | null
  phone?: string | null
  gstin?: string | null
  address?: string | null
  city?: string | null
  state?: string | null
}

interface InvoiceInfo {
  invoice_number: string
  amount: number
  tax_amount: number
  total_amount: number
  issue_date: string
  due_date: string
  description?: string | null
  status: string
}

export async function generateInvoicePDF(
  business: BusinessInfo,
  client: ClientInfo,
  invoice: InvoiceInfo
): Promise<ArrayBuffer> {
  const { jsPDF } = await import('jspdf')
  const autoTable = (await import('jspdf-autotable')).default

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const w = doc.internal.pageSize.getWidth()
  const margin = 20

  // Header
  doc.setFillColor(37, 99, 235) // blue-600
  doc.rect(0, 0, w, 40, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text('INVOICE', margin, 20)

  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text(business.name, margin, 28)
  if (business.gstin) doc.text(`GSTIN: ${business.gstin}`, margin, 33)

  // Invoice number on right
  doc.setFontSize(12)
  doc.setFont('helvetica', 'bold')
  doc.text(`#${invoice.invoice_number}`, w - margin, 20, { align: 'right' })
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.text(`Date: ${formatDate(invoice.issue_date)}`, w - margin, 27, { align: 'right' })
  doc.text(`Due: ${formatDate(invoice.due_date)}`, w - margin, 33, { align: 'right' })

  // Business & Client details
  doc.setTextColor(0, 0, 0)
  let y = 55

  doc.setFontSize(9)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(107, 114, 128)
  doc.text('FROM', margin, y)
  doc.text('BILL TO', w / 2, y)

  y += 5
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(17, 24, 39)

  const fromLines = [
    business.name,
    business.address || '',
    [business.city, business.state, business.pincode].filter(Boolean).join(', '),
    business.phone || '',
    business.email || '',
  ].filter(Boolean)

  const toLines = [
    client.name,
    client.address || '',
    [client.city, client.state].filter(Boolean).join(', '),
    client.gstin ? `GSTIN: ${client.gstin}` : '',
    client.phone || '',
    client.email || '',
  ].filter(Boolean)

  doc.setFontSize(9)
  fromLines.forEach((line, i) => {
    if (i === 0) doc.setFont('helvetica', 'bold')
    else doc.setFont('helvetica', 'normal')
    doc.text(line, margin, y + i * 5)
  })

  toLines.forEach((line, i) => {
    if (i === 0) doc.setFont('helvetica', 'bold')
    else doc.setFont('helvetica', 'normal')
    doc.text(line, w / 2, y + i * 5)
  })

  y += Math.max(fromLines.length, toLines.length) * 5 + 12

  // Items table
  autoTable(doc, {
    startY: y,
    head: [['Description', 'Amount']],
    body: [
      [invoice.description || 'Professional Services', formatCurrency(invoice.amount)],
      [`GST (${invoice.tax_amount > 0 ? ((invoice.tax_amount / invoice.amount) * 100).toFixed(0) : 0}%)`, formatCurrency(invoice.tax_amount)],
    ],
    foot: [['Total', formatCurrency(invoice.total_amount)]],
    margin: { left: margin, right: margin },
    headStyles: { fillColor: [37, 99, 235], textColor: 255, fontStyle: 'bold', fontSize: 10 },
    footStyles: { fillColor: [241, 245, 249], textColor: [17, 24, 39], fontStyle: 'bold', fontSize: 11 },
    styles: { fontSize: 10, cellPadding: 4 },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
  })

  const finalY = (doc as any).lastAutoTable.finalY + 15

  // Payment status
  const isPaid = invoice.status === 'paid'
  doc.setFillColor(isPaid ? 220 : 254, isPaid ? 252 : 226, isPaid ? 231 : 226)
  doc.setDrawColor(isPaid ? 134 : 249, isPaid ? 239 : 115, isPaid ? 172 : 22)
  doc.roundedRect(margin, finalY, w - margin * 2, 12, 3, 3, 'FD')
  doc.setFontSize(10)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(isPaid ? 21 : 146, isPaid ? 128 : 64, isPaid ? 61 : 14)
  doc.text(isPaid ? '✓ PAID' : `⚠ OUTSTANDING — Please pay by ${formatDate(invoice.due_date)}`, w / 2, finalY + 8, { align: 'center' })

  // Footer
  doc.setTextColor(156, 163, 175)
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.text('Generated by CollectEase · collectease.in', w / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' })

  return doc.output('arraybuffer')
}

export async function generateLegalNoticePDF(
  business: BusinessInfo,
  client: ClientInfo,
  invoice: InvoiceInfo
): Promise<ArrayBuffer> {
  const { jsPDF } = await import('jspdf')

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const w = doc.internal.pageSize.getWidth()
  const margin = 25
  const daysOverdue = getDaysOverdue(invoice.due_date)

  let y = 25

  // Title
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(17, 24, 39)
  doc.text('LEGAL NOTICE', w / 2, y, { align: 'center' })
  y += 6
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.text('(Under MSME Development Act, 2006)', w / 2, y, { align: 'center' })
  y += 10

  doc.setDrawColor(229, 231, 235)
  doc.line(margin, y, w - margin, y)
  y += 8

  // Date and ref
  doc.setFontSize(10)
  doc.text(`Date: ${formatDate(new Date().toISOString())}`, margin, y)
  doc.text(`Ref: LEGAL-${invoice.invoice_number}`, w - margin, y, { align: 'right' })
  y += 12

  // Sender
  doc.setFont('helvetica', 'bold')
  doc.text('From:', margin, y)
  doc.setFont('helvetica', 'normal')
  y += 5
  const fromInfo = [
    business.name,
    business.address || '',
    [business.city, business.state, business.pincode].filter(Boolean).join(', '),
    business.gstin ? `GSTIN: ${business.gstin}` : '',
    business.phone || '',
    business.email || '',
  ].filter(Boolean)

  fromInfo.forEach(line => { doc.text(line, margin + 5, y); y += 5 })
  y += 6

  // Recipient
  doc.setFont('helvetica', 'bold')
  doc.text('To:', margin, y)
  doc.setFont('helvetica', 'normal')
  y += 5
  const toInfo = [
    client.name,
    client.address || '',
    [client.city, client.state].filter(Boolean).join(', '),
    client.gstin ? `GSTIN: ${client.gstin}` : '',
    client.phone || '',
    client.email || '',
  ].filter(Boolean)

  toInfo.forEach(line => { doc.text(line, margin + 5, y); y += 5 })
  y += 8

  // Subject
  doc.setFont('helvetica', 'bold')
  doc.setFontSize(11)
  doc.text(`Subject: Recovery of outstanding payment of ${formatCurrency(invoice.total_amount)} against Invoice No. ${invoice.invoice_number}`, margin, y, { maxWidth: w - margin * 2 })
  y += 12

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)

  const body = [
    `Sir/Madam,`,
    ``,
    `Under instructions from our client M/s ${business.name}, we hereby serve this Legal Notice upon you as under:`,
    ``,
    `1. That our client supplied goods/services to your organization as per Invoice No. ${invoice.invoice_number} dated ${formatDate(invoice.issue_date)} for a sum of ${formatCurrency(invoice.amount)} plus GST of ${formatCurrency(invoice.tax_amount)}, totalling ${formatCurrency(invoice.total_amount)}.`,
    ``,
    `2. That the said invoice was payable on or before ${formatDate(invoice.due_date)}. Despite the expiry of the due date ${daysOverdue} days ago, and despite repeated reminders, you have willfully and deliberately failed and neglected to make payment of the said amount.`,
    ``,
    `3. That your failure to pay constitutes a breach of contract and is in violation of Section 16 of the MSME Development Act, 2006, which mandates payment within 45 days from the date of acceptance.`,
    ``,
    `4. You are hereby called upon to pay the outstanding amount of ${formatCurrency(invoice.total_amount)} along with interest at 3 times the bank rate as per Section 16 of the MSME Development Act, 2006, within 15 days of receipt of this notice.`,
    ``,
    `5. In case of failure to comply, our client will be compelled to initiate legal proceedings against you including filing an application before the MSME Facilitation Council / Samadhaan portal for recovery of dues, without further notice, at your cost and risk.`,
    ``,
    `Yours faithfully,`,
    ``,
    business.name,
    business.phone || '',
    business.email || '',
  ]

  body.forEach(line => {
    if (line === '') { y += 4; return }
    const lines = doc.splitTextToSize(line, w - margin * 2)
    doc.text(lines, margin, y)
    y += lines.length * 5 + 1
  })

  // Footer
  doc.setTextColor(156, 163, 175)
  doc.setFontSize(8)
  doc.text('Generated by CollectEase · collectease.in', w / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' })

  return doc.output('arraybuffer')
}

export async function generateMSMEComplaintPDF(
  business: BusinessInfo,
  client: ClientInfo,
  invoice: InvoiceInfo
): Promise<ArrayBuffer> {
  const { jsPDF } = await import('jspdf')

  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const w = doc.internal.pageSize.getWidth()
  const margin = 25

  let y = 25
  doc.setFontSize(14)
  doc.setFont('helvetica', 'bold')
  doc.text('MSME SAMADHAAN — COMPLAINT DRAFT', w / 2, y, { align: 'center' })
  y += 7
  doc.setFontSize(9)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(107, 114, 128)
  doc.text('Application for Recovery of Dues under MSMED Act, 2006', w / 2, y, { align: 'center' })
  y += 10
  doc.setTextColor(0, 0, 0)

  doc.setDrawColor(229, 231, 235)
  doc.line(margin, y, w - margin, y)
  y += 10

  const fields = [
    ['Applicant (Seller) Name', business.name],
    ['Applicant GSTIN', business.gstin || 'N/A'],
    ['Applicant Contact', [business.phone, business.email].filter(Boolean).join(' / ')],
    ['Applicant Address', [business.address, business.city, business.state, business.pincode].filter(Boolean).join(', ')],
    ['', ''],
    ['Respondent (Buyer) Name', client.name],
    ['Respondent GSTIN', client.gstin || 'N/A'],
    ['Respondent Contact', [client.phone, client.email].filter(Boolean).join(' / ')],
    ['Respondent Address', [client.address, client.city, client.state].filter(Boolean).join(', ')],
    ['', ''],
    ['Invoice Number', invoice.invoice_number],
    ['Invoice Date', formatDate(invoice.issue_date)],
    ['Invoice Amount', formatCurrency(invoice.amount)],
    ['GST Amount', formatCurrency(invoice.tax_amount)],
    ['Total Amount Claimed', formatCurrency(invoice.total_amount)],
    ['Payment Due Date', formatDate(invoice.due_date)],
    ['Days Overdue', `${getDaysOverdue(invoice.due_date)} days`],
    ['', ''],
    ['Nature of Dispute', 'Non-payment of dues for services/goods supplied'],
    ['Relief Sought', `Recovery of ${formatCurrency(invoice.total_amount)} along with interest at 3x bank rate`],
  ]

  doc.setFontSize(10)
  fields.forEach(([label, value]) => {
    if (!label && !value) { y += 3; return }
    doc.setFont('helvetica', 'bold')
    doc.text(`${label}:`, margin, y)
    doc.setFont('helvetica', 'normal')
    const lines = doc.splitTextToSize(value, w - margin - 90)
    doc.text(lines, margin + 80, y)
    y += lines.length * 5 + 2
  })

  y += 10
  doc.setFont('helvetica', 'bold')
  doc.text('Declaration:', margin, y)
  y += 6
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(9)
  const declaration = `I/We hereby declare that the above information is true and correct to the best of my/our knowledge and belief. I/We have not approached any court of law or any other authority in respect of the above dispute.`
  const declLines = doc.splitTextToSize(declaration, w - margin * 2)
  doc.text(declLines, margin, y)
  y += declLines.length * 5 + 15

  doc.text('Signature: ___________________________', margin, y)
  y += 6
  doc.text(`Name: ${business.name}`, margin, y)
  y += 6
  doc.text(`Date: ${formatDate(new Date().toISOString())}`, margin, y)

  doc.setTextColor(156, 163, 175)
  doc.setFontSize(8)
  doc.text('Draft generated by CollectEase · Submit at: msmesamadhaan.gov.in', w / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' })

  return doc.output('arraybuffer')
}

export async function generateReportCSV(invoices: any[]): Promise<string> {
  const headers = ['Invoice Number', 'Client', 'Amount', 'GST', 'Total', 'Issue Date', 'Due Date', 'Status', 'Paid Date', 'Days Overdue']
  const rows = invoices.map(inv => [
    inv.invoice_number,
    inv.client?.name || '',
    inv.amount,
    inv.tax_amount,
    inv.total_amount,
    inv.issue_date,
    inv.due_date,
    inv.status,
    inv.paid_at ? inv.paid_at.split('T')[0] : '',
    inv.status === 'overdue' ? getDaysOverdue(inv.due_date) : '',
  ])

  return [headers, ...rows].map(row => row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(',')).join('\n')
}
